/**:
  ros__parameters:
    wheel_radius: 0.033
    track_width: 0.16
    motor_cmd_max: 265.0
    motor_cmd_per_rad_sec: 0.024
    encoder_ticks_per_rad: 651.90 # Rounded from 2^12/(2pi)
    collision_radius: 0.11